import timeToolsImg from "../imgs/timetools.png";
import questionsImg from "../imgs/questionsapi.png";
import notesImg from "../imgs/notesapp.png";
import liveUserImg from "../imgs/liveuserapi.png";
import passwordGenImg from "../imgs/passwordgenerator.png";
import randomChoiceImg from "../imgs/randomchoicepicker.png";
import tmbCalculator from "../imgs/tmb_calculator.png";
import shoppingList from "../imgs/shopping-list.png";
import questionsAPI from "../imgs/questions-api.png";
import notesReact from "../imgs/notes-react.png";
import movieApi from "../imgs/movie-api.png";
import nikelp from "../imgs/nikelp.png";
import gymWireframe from "../imgs/gym-wireframe.png";
import emailMarketingBFMS from "../imgs/email-marketing-bfms.png";
import interiorDesignWireframe from "../imgs/interior-design-wireframe.png";
import pomodoroTask from "../imgs/pomodorotask.png";

export const projects = [
  {
    title: "Pomodoro Task",
    site: "https://oleosb.github.io/pomodoro-task",
    img: pomodoroTask,
    description: "Gerenciador de tempo e tarefas.",
    tags: [
      "pomodoro",
      "task",
      "html",
      "css",
      "javascript",
      "react",
      "js",
      "code",
      "codigo",
      "tempo",
      "tarefa",
      "gerenciador",
      "time",
      "npm",
    ],
    category: "#F8D210",
  },
  {
    title: "Wireframe D. de Interiores",
    behance:
      "https://www.behance.net/gallery/153809055/interior-design-uiux-design",
    img: interiorDesignWireframe,
    description: "Wireframe para website de design de interiores.",
    tags: [
      "design",
      "figma",
      "adobe",
      "illustrator",
      "desenho",
      "ui",
      "ux",
      "interface",
      "user",
      "usuario",
    ],
    category: "#C55FFC",
  },
  {
    title: "Nike Landing Page",
    gitHub: "https://github.com/oleosb/nike-landing_page",
    site: "https://oleosb.github.io/nike-landing-page/",
    img: nikelp,
    description: "Landing Page do tênis Nike Metcon 8.",
    tags: [
      "nike",
      "landing",
      "page",
      "javascript",
      "css",
      "html",
      "cart",
      "store",
      "shoes",
      "paginadevendas",
      "carrinho",
      "loja",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Calculadora de TMB",
    gitHub: "https://github.com/oleosb/calculadora_tmb-reactjs-",
    site: "https://oleosb.github.io/calculadora-tmb-reactjs",
    img: tmbCalculator,
    description:
      "Calcula a Taxa Metabólica Basal e IMC, informando o usuário quantas calorias podem ser ingeridas diariamente",
    tags: [
      "calculator",
      "calculadora",
      "html",
      "css",
      "javascript",
      "react",
      "js",
      "imc",
      "tmb",
      "taxa",
      "metabolica",
      "basal",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Lista de Compras",
    gitHub: "https://github.com/oleosb/shopping_list-reactjs",
    site: "https://oleosb.github.io/shopping-list-reactjs/",
    img: shoppingList,
    description:
      "Crie sua lista de compras. Adicione, remova e altere a quantidade dos itens.",
    tags: [
      "shopping",
      "list",
      "compras",
      "lista",
      "react",
      "js",
      "javascript",
      "html",
      "css",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Wireframe Academia",
    behance: "https://www.behance.net/gallery/153808403/gym-uiux-design",
    img: gymWireframe,
    description: "Wireframe para website de academia.",
    tags: [
      "design",
      "figma",
      "adobe",
      "illustrator",
      "desenho",
      "ui",
      "ux",
      "interface",
      "user",
      "usuario",
      "gym",
      "academia",
    ],
    category: "#C55FFC",
  },
  {
    title: "Email Marketing BFMS",
    behance: "https://www.behance.net/gallery/153809541/Email-Marketing-BFMS?",
    img: emailMarketingBFMS,
    description: "Design de email marketing para BFMS.",
    tags: [
      "design",
      "figma",
      "adobe",
      "illustrator",
      "desenho",
      "ui",
      "ux",
      "interface",
      "user",
      "usuario",
      "html",
      "css",
    ],
    category: "#C55FFC",
  },
  {
    title: "Questions API",
    gitHub: "https://github.com/oleosb/questionApp_api-reactsjs-",
    site: "https://oleosb.github.io/question-api-reactjs/",
    img: questionsAPI,
    description:
      "Jogo de perguntas como filtro para quantidade de perguntas e categorias.",
    tags: [
      "javascript",
      "react",
      "js",
      "html",
      "css",
      "api",
      "quiz",
      "pergunta",
      "resposta",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Notes App",
    gitHub: "https://github.com/oleosb/notesApp-reactjs-",
    img: notesReact,
    description:
      "Aplicativo Web de Anotações que permite o usuário a criar, editar e excluir notas. Todas as anotações são armazenadas no localStorage.",
    tags: [
      "javascript",
      "react",
      "js",
      "html",
      "css",
      "note",
      "nota",
      "list",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Movie App",
    gitHub: "https://github.com/oleosb/movieApp_tmdbApi-reactjs-",
    img: movieApi,
    description: "Aplicativo de filmes e séries desenvolvido com API do TMDB.",
    tags: [
      "javascript",
      "react",
      "js",
      "html",
      "css",
      "filme",
      "movie",
      "serie",
      "netflix",
      "api",
      "tmdb",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Time Tools",
    gitHub: "https://github.com/oleosb/sb-tools",
    img: timeToolsImg,
    description:
      "O SB Time Tools é um conjunto de ferramentas composto por cronômetro, timer, pomodoro e tabata como objetivo de ajudar o usuário a administrar o tempo para determinadas atividades.",
    tags: [
      "cronometro",
      "timer",
      "pomodoro",
      "tabata",
      "javascript",
      "js",
      "html",
      "css",
      "tempo",
      "cronometer",
      "countdown",
      "sb",
      "tools",
      "ferramentas",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Live User Filter",
    gitHub: "https://github.com/oleosb/live-filter-api",
    img: liveUserImg,
    description:
      "O Live Filter permite pesquisar e filtrar pessoas por seu nome e/ou localização.",
    tags: [
      "javascript",
      "js",
      "html",
      "css",
      "filtro",
      "filter",
      "user",
      "usuario",
      "live",
      "online",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Password Generator",
    gitHub: "https://github.com/oleosb/password-generator",
    img: passwordGenImg,
    description:
      "Gerador de senhas. Permite o usuário escolher a quantidade de caracteres e incluir letras maiúsculas, minúsculas, símbolos e números.",
    tags: [
      "javascript",
      "js",
      "html",
      "css",
      "senha",
      "password",
      "gerador",
      "generator",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Random Choice Picker",
    gitHub: "https://github.com/oleosb/random-picker",
    img: randomChoiceImg,
    description: "Sorteio de opções inseridas pelo usuário.",
    tags: [
      "javascript",
      "js",
      "html",
      "css",
      "random",
      "choice",
      "picker",
      "aleatorio",
      "escolha",
      "aleatoria",
      "sorteio",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Questions API",
    gitHub: "https://github.com/oleosb/questions-api",
    img: questionsImg,
    description:
      "Jogo de perguntas como filtro para quantidade de perguntas e categorias.",
    tags: [
      "javascript",
      "js",
      "html",
      "css",
      "api",
      "quiz",
      "pergunta",
      "resposta",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
  {
    title: "Notes App",
    gitHub: "https://github.com/oleosb/notes-app",
    img: notesImg,
    description:
      "Aplicativo Web de Anotações que permite o usuário a criar, editar e excluir notas. Todas as anotações são armazenadas no localStorage.",
    tags: [
      "javascript",
      "js",
      "html",
      "css",
      "note",
      "nota",
      "list",
      "local",
      "storage",
      "code",
      "codigo",
    ],
    category: "#F8D210",
  },
];
